name: Go
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19.3
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
          cache: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod tidy

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race `go list ./... | grep -v "aws\|sftp\|http"`
