name: Go
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.18.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod tidy -compat=1.18

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race `go list ./... | grep -v "aws\|sftp\|http"`
